"""Migración inicial

Revision ID: c9c2e3f7bd45
Revises: 
Create Date: 2025-05-13 19:10:29.902039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c2e3f7bd45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=80), nullable=False),
    sa.Column('contraseña', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contraseña'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('amistades',
    sa.Column('id_usuario_1', sa.Integer(), nullable=False),
    sa.Column('id_usuario_2', sa.Integer(), nullable=False),
    sa.CheckConstraint('id_usuario_1 != id_usuario_2', name='check_usuarios_diferentes'),
    sa.ForeignKeyConstraint(['id_usuario_1'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_2'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_usuario_1', 'id_usuario_2')
    )
    op.create_table('publicaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicaciones')
    op.drop_table('amistades')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
