"""Se agregó el campo imagen a la tabla usuario

Revision ID: 00237a1e5680
Revises: 9a76d26d4998
Create Date: 2025-07-14 12:23:50.815909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00237a1e5680'
down_revision = '9a76d26d4998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
