"""Se elimina la constrait unique de contraseña

Revision ID: 16ec926247bd
Revises: 8d1d410a4cef
Create Date: 2025-05-16 21:35:40.647948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ec926247bd'
down_revision = '8d1d410a4cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('usuarios_contraseña_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint('usuarios_contraseña_key', ['contraseña'])

    # ### end Alembic commands ###
