"""Se agregó el campo seguidores a la tabla usuarios

Revision ID: 81a4265cb9c4
Revises: d6282c6a14f0
Create Date: 2025-07-22 10:43:35.043614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a4265cb9c4'
down_revision = 'd6282c6a14f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seguidores', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('seguidores')

    # ### end Alembic commands ###
