"""Se agrega campo contenido a tabla publicacion

Revision ID: 8d1d410a4cef
Revises: c9c2e3f7bd45
Create Date: 2025-05-13 19:20:17.267661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1d410a4cef'
down_revision = 'c9c2e3f7bd45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenido', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.drop_column('contenido')

    # ### end Alembic commands ###
