"""Se agregó el campo nacimiento a la tabla usuario

Revision ID: 9a76d26d4998
Revises: 6a6466a6d9fb
Create Date: 2025-07-11 20:06:09.022887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a76d26d4998'
down_revision = '6a6466a6d9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nacimiento', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('nacimiento')

    # ### end Alembic commands ###
