"""Se modificó la tabla Amistades por la tabla Seguidores

Revision ID: d6282c6a14f0
Revises: 857bcd8d127f
Create Date: 2025-07-19 11:34:13.316673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6282c6a14f0'
down_revision = '857bcd8d127f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seguidores',
    sa.Column('id_seguidor', sa.Integer(), nullable=False),
    sa.Column('id_seguido', sa.Integer(), nullable=False),
    sa.CheckConstraint('id_seguidor != id_seguido', name='check_usuarios_diferentes'),
    sa.ForeignKeyConstraint(['id_seguido'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_seguidor'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_seguidor', 'id_seguido')
    )
    op.drop_table('amistades')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amistades',
    sa.Column('id_usuario_1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_usuario_2', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('id_usuario_1 <> id_usuario_2', name='check_usuarios_diferentes'),
    sa.ForeignKeyConstraint(['id_usuario_1'], ['usuarios.id'], name='amistades_id_usuario_1_fkey'),
    sa.ForeignKeyConstraint(['id_usuario_2'], ['usuarios.id'], name='amistades_id_usuario_2_fkey'),
    sa.PrimaryKeyConstraint('id_usuario_1', 'id_usuario_2', name='amistades_pkey')
    )
    op.drop_table('seguidores')
    # ### end Alembic commands ###
